-- local client = vim.lsp.start_client {
-- 	name = "rs-lsp",
-- 	cmd = {"/home/wesleylewis/Desktop/Rust_projects/lsp-rs/target/release/lsp-rs"},
-- }
--
-- if not client then
-- 	vim.notify "build not made proper"
-- 	return
-- end
--
-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = "markdown",
-- 	callback = function()
-- 		vim.lsp.buf_attach_client(0, client)
-- 	end,
-- })
